#!/usr/bin/python3
# COMP3311 20T2 Final Exam
# Q7: tracklist for album, given by Albums.id
#     show performers/instruments for each track

import sys
import psycopg2

# ... put helper functions here ...

db = None
cur = None
usage = f"Usage: {sys.argv[0]} AlbumID"
oldquery = """
select a.title, a.year, a.genre, s.title, s.trackNo, p.name, po.instrument
from albums a
join songs s on (s.on_album = a.id)
left outer join playson po on (po.song = s.id)
left outer join performers p on (p.id = po.performer)
where a.id = %s
group by a.id, s.id, p.id, a.title, a.year, a.genre, s.title, s.trackNo, p.name, po.instrument
order by s.trackNo, p.name, po.instrument;
"""
query = """
select a.title, a.year, a.genre, s.title, s.trackNo, p.name, instrumentsOf(p.id, s.id)
from albums a
join songs s on (s.on_album = a.id)
left outer join playson po on (po.song = s.id)
left outer join performers p on (p.id = po.performer)
where a.id = %s
group by a.id, s.id, p.id, a.title, a.year, a.genre, s.title, s.trackNo, p.name
order by s.trackNo, p.name, instrumentsOf;
"""

# process command-line args

if len(sys.argv) < 2:
   print(usage)
   exit(1)
albumID = sys.argv[1]
if not albumID.isnumeric():
   print(usage)
   exit(1)

try:
   db = psycopg2.connect("dbname=music")
   cursor = db.cursor()
   cursor.execute(query, [albumID])
   if (cursor.rowcount == 0):
      print("Invalid album ID")
   else:
      doneTitle = False
      currSong = None
      for row in cursor.fetchall():
         aTitle, aYear, aGenre, sTitle, sTrackNo, pName, instruments = row
         if (not doneTitle):
            print(f"{aTitle} ({aYear}) ({aGenre})") 
            print(40*'=')
            doneTitle = True
         if (currSong != sTitle):
            print("%2d. %s" % (sTrackNo, sTitle))
            currSong = sTitle
         if (pName == None):
            pName = 'The whole group'
            print("%8s%s" % (' ', pName))
         else:
            print("%8s%s: %s" % (' ', pName, instruments))
except psycopg2.Error as err:
   print("DB error: ", err)
finally:
   if cur:
      cur.close()
   if db:
      db.close()

