#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print name, year, ratings of top N movies

import sys
import psycopg2
#from helpers import whatever, functions, you, need

# define any local helper functions here

# set up some globals

usage = "Usage: best [N]"
db = None

# process command-line args

n: int = 10
argc = len(sys.argv)
if (argc > 1):
  n = sys.argv[1]
  print(isinstance(n, int))
  if (not isinstance(n, int) or n < 1):
    print(usage)
    exit(0)



# manipulate database

try:
  db = psycopg2.connect("dbname=imdb")
  # ... add your code here ...
except psycopg2.Error as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()

