#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print info about different releases for Movie

import sys
import psycopg2
#from helpers import whatever, functions, you, need

# define any local helper functions here

# set up some globals

usage = "Usage: rels 'PartialMovieTitle'"
db = None

# process command-line args

argc = len(sys.argv)
if (argc < 2):
  print(usage)
  exit(0)
title_regex = sys.argv[1]
print(title_regex)

# manipulate database

try:
  db = psycopg2.connect("dbname=imdb")
  cursor = db.cursor()
  query = """
  select *
  from movies
  where title ~* %s
  """
  cursor.execute(query, [title_regex])
  print(cursor.rowcount)
  for row in cursor.fetchall():
    print(row)
except psycopg2.Error as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()

