#!/usr/bin/python3
# COMP3311 20T2 Final Exam
# Q6: discography for one group, given by Groups.id

import sys
import psycopg2

# ... put helper functions here ...

db = None
cur = None
usage = f"Usage: {sys.argv[0]} GroupID"
query = """
select g.name, a.title, a.year, a.genre, s.trackNo, s.title, s.length
from groups g
join albums a on (a.made_by = g.id)
join songs s on (s.on_album = a.id)
where g.id = %s
group by g.id, a.title, a.year, a.genre, s.trackNo, s.title, s.length
order by a.year, a.title, s.trackNo
"""

# process command-line args

if len(sys.argv) < 2:
   print(usage)
   exit(1)
groupID = sys.argv[1]
if not groupID.isnumeric():
   print(usage)
   exit(1)

try:
   db = psycopg2.connect("dbname=music")
   cursor = db.cursor()
   cursor.execute(query, [groupID])
   if (cursor.rowcount == 0):
      print("Invalid group ID")
   else:
      doneTitle = False
      currTitle = None
      for row in cursor.fetchall():
         gName, aTitle, aYear, aGenre, sTrackNo, sTitle, sLen = row
         if (not doneTitle):
            print(f"Discography for {gName}")
            doneTitle = True
         if (aTitle != currTitle):
            currTitle = aTitle
            print(20 * '-')
            print(f"{aTitle} ({aYear}) ({aGenre})")
            print(20 * '-')
         print("%2d. %s (%d:%02d)" % (sTrackNo, sTitle, sLen // 60, sLen % 60))
except psycopg2.Error as err:
   print("DB error: ", err)
finally:
   if cur:
      cur.close()
   if db:
      db.close()

